name: CI Demo Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Run a simple script
      run: echo "Hello, DevOps Day 4! CI workflow is running."